### ISSUE TITLE
Require status checks to pass in order to merge to master

### ISSUE THREAD

**Issue by TheButlah** [zroga95/town_generator#6]
@zroga95 Depending on your opinion, it would be nice to require status checks (the CI) to pass before merging to master. That would ensure that the code on master always works. Right now the tests run, but it doesn't matter if they report an issue (you can click the github actions tab to see the CI)

The consequence of this is that it requires everyone to work on a branch separate from master, so that you can push commits. Then you can submit a PR to merge into master, assuming the CI passes. The workflow would basically be this: https://guides.github.com/introduction/flow/

**Comment by zroga95** [comment]
Added a rule for settings to require status checks
